r"""Convergence package default values."""

__ABS_TOL = 1e-18
__REL_TOL = 1e-09

__RELATIVE_HALF_WIDTH_ESTIMATE_ABS_TOL = 1e-06

__CONFIDENCE_COEFFICIENT = 0.95
__EQUILIBRATION_LENGTH_ESTIMATE = 0
__HEIDEL_WELCH_NUMBER_POINTS = 50
__BATCH_SIZE = 5
__FFT = True
__SCALE_METHOD = 'translate_scale'
__WITH_CENTERING = False
__WITH_SCALING = False,
__TEST_SIZE = None
__TRAIN_SIZE = None
__POPULATION_STANDARD_DEVIATION = None
__SI = None
__MINIMUM_CORRELATION_TIME = None
__UNCORRELATED_SAMPLE_INDICES = None
__SAMPLE_METHOD = None

__IGNORE_END = None

__NSKIP = 1

__SEED = None

__all__ = [
    '__ABS_TOL',
    '__REL_TOL',
    '__RELATIVE_HALF_WIDTH_ESTIMATE_ABS_TOL',
    '__CONFIDENCE_COEFFICIENT',
    '__EQUILIBRATION_LENGTH_ESTIMATE',
    '__HEIDEL_WELCH_NUMBER_POINTS',
    '__BATCH_SIZE',
    '__FFT',
    '__SCALE_METHOD',
    '__WITH_CENTERING',
    '__WITH_SCALING',
    '__TEST_SIZE',
    '__TRAIN_SIZE',
    '__POPULATION_STANDARD_DEVIATION',
    '__SI',
    '__MINIMUM_CORRELATION_TIME',
    '__UNCORRELATED_SAMPLE_INDICES',
    '__SAMPLE_METHOD',
    '__IGNORE_END',
    '__NSKIP',
    '__SEED',
]
